onboarding = false

[terminal]
default_shell = "/usr/local/bin/fish"
shell_mode = "login"

[ui]
agent_panel_sort = "spaces"

[keys]
prefix = "backtick"
previous_tab = "shift+left"
next_tab = "shift+right"
switch_tab = ""
switch_workspace = "prefix+1..9"
